version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: discord.js
    versions:
    - 13.5.0
  - dependency-name: eslint
    versions:
    - 8.2.0